### ISSUE TITLE
La clave secreta sigue vigente?

### ISSUE THREAD

**Issue by Darumn** [rmon-vfer/wallapop_secret#1]
Hola, estoy intentando hacer una aplicación que haga consultas de búsqueda de nuevos productos a wallapop para interpretar nuevas publicaciones y he visto que es necesario incluir el campo X-Signature en la request para que el API conteste correctamente. He encontrado este script para generar dicho campo pero tras hacer varios intentos con diferentes "endpoints" no consigo generar el mismo valor para el campo X-Signature de una request que he capturado de ejemplo (utilizo el timestamp de la misma request para generarlo). Sabes si han podido actualizar esta clave secreta? Podrías indicarme un ejemplo del valor que tendría que tener el parámetro "endpoint" para una determinada url de búsqueda de wallapop?

Muchas gracias por tu ayuda,
Un saludo.

**Comment by rmonvfer** [comment]
Hola,

Hace ya bastante que le hice ingeniería inversa a la API de Wallapop (estaba haciendo un wrapper en python) y se lo notifiqué por correo a ellos para que hiciesen algo (seguridad, ¿que es eso?) de todas formas, puedo echarle un vistazo a ver si la saco otra vez.
Respecto al ejemplo, si buscases "hacking" en la barra de búsqueda, se llamaría al siguiente endpoint de la API:
`https://api.wallapop.com/api/v3/suggesters/search?keyword=hacking&language=es_ES`
La cabecera que nos interesa es `X-Signature: JiQOYz/QDl26in3UrBs8K8RThgXHRjvGizOnRHVltQc=`, aunque también convendría tener a mano la timestamp para saber con que valor se ha generado la signature (en las pruebas que hice, la timestamp que envia es la misma que usa para generarla). En este caso es: `Timestamp: 1600339727696`.
No tengo muy claro si consideran que el endpoint es "suggesters/search" o solo "suggesters", pero podemos comprobarlo usando el script, en ambos casos el "method" es `GET`:
 - Usando `suggesters/search`: a2RpbgewuetjIO32rxvcf5fCjs700MrsgMcjhZcLZkc=
 - Usando `suggesters`: VyzDtsO45lDGi0ML+qxyQkQMt7LhkNSreBKgcYX/+pU=
Así que parece que han cambiado la clave o el método de generación.

Si la encuentro actualizaré el repo (activa las notificaciones)

Un saludo

**Comment by rmonvfer** [comment]
![imagen](https://user-images.githubusercontent.com/42870707/93462776-20399580-f8e7-11ea-9de6-88da09e10e60.png)
Bueno, ha sido bastante corta la búsqueda xD.
La nueva clave es: Tm93IHRoYXQgeW91J3ZlIGZvdW5kIHRoaXMsIGFyZSB5b3UgcmVhZHkgdG8gam9pbiB1cz8gam9ic0B3YWxsYXBvcC5jb20==
Que es básicamente el mismo texto que antes: "Now that you've found this, are you ready to join us? jobs@wallapop.com" pero con alguna pequeña modificación. Los muy cabroncetes han añadido un "=" al final de la cadena de Base64 para que no se pueda decodificar a la primera, hay que eliminarla y ya se obtiene el texto plano: Tm93IHRoYXQgeW91J3ZlIGZvdW5kIHRoaXMsIGFyZSB5b3UgcmVhZHkgdG8gam9pbiB1cz8gam9ic0B3YWxsYXBvcC5jb20=

Un saludo!

**Comment by Darumn** [comment]
Genial! Muchísimas gracias por tu ayuda, probaré con esta nueva clave a ver si lo consigo :)

Gracias!

**Comment by imuhammadumair** [comment]
Hello ,
I am also facing this issue
